FROM postgres:15

# Install jq
RUN apt-get update && \
    apt-get install -y jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy and make script executable
COPY create_table.sh /create_table.sh
RUN chmod +x /create_table.sh

ENTRYPOINT ["/create_table.sh"]
